runtime: nodejs22
instance_class: F2

env_variables:
  NODE_ENV: "production"
  NPM_CONFIG_LEGACY_PEER_DEPS: "true"
  NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL}
  NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}

entrypoint: npm install --legacy-peer-deps && npm run build && npm start

# Optional: static files (only if using `npm run export`)
handlers:
- url: /
  static_files: out/index.html
  upload: out/index.html
- url: /(.*)
  static_files: out/\1
  upload: out/(.*)
